on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Finalise
      run: |
        echo "ALL"
        ls -a
        echo "TARGET"
        ls ./target -a
        echo "RELEASE"
        ls ./target/release -a
        cp ./target/release/weather_wallpaper.exe .
        zip weather_wallpaper.zip weather_wallpaper.exe
            
